### PR TITLE
Packaging using PIP

### PR DESCRIPTION
**Pull request by bavovanachte**
Infrastucture changes in order to publish to pip.

### CODE REVIEW

**Comment by pfalcon** [comment]
Thanks for the patch. Well, that's definitely not how I'd write it, not from the beginning at least, so I just assume you've tested it to work as expected, and push it as is. Published: https://pypi.python.org/pypi/sphinx_selective_exclude .

Please stay around in case someone reports an issue against the new version ;-) (I myself so far using the old plugin directory structure for my project).

**Comment by bavovanachte** [comment]
I don't have a strong personal preference towards this directory structure, I just based it on many of the other pypi packages out there. I guess for setup.py to detect the python as a module from the root directory, it needs to be in a subfolder with an __init__.py. Although I'm not 100% sure about that.

**Comment by pfalcon** [comment]
Sure, you did it correct way, it should be a proper Python package to be packaged as a distribution package (tarball/egg/wheel). My point is that I didn't test that it gets properly picked up by sphinx after this change, so I hope you did ;-).

**Comment by bavovanachte** [comment]
Sadly, it doesn't seem to work.

I tested locally using ```python setup.py bdist_wheel```. This works.
However, when doing it through ```python setup.py sdist``` it doesn't, and it complains about not finding README.md. I saw that this is indeed not included in the tarball.

I'll have to check what's the difference there. Do you have any idea perhaps?

**Comment by bavovanachte** [comment]
Ok, so it seems sdist doesn't include README.md by default (but it does include README and README.txt)

I'll create a new PR with a MANIFEST.in

**Comment by bavovanachte** [comment]
Fix proposed in https://github.com/pfalcon/sphinx_selective_exclude/pull/5

**Comment by pfalcon** [comment]
Well, as the link https://pypi.python.org/pypi/sphinx_selective_exclude above shows, I was able to sdist and publish it (and that's why I merged it). It can be easily seen that there's a cosmetic issue of markdown not being rendered properly, I'm not sure if that's metadata problem or PyPI doesn't support it, but again, package was created and published successfully.

So, my question is more - please try to install it from PyPI and check that it works as expected when installed this way (I won't be able to test that anytime soon).

**Comment by bavovanachte** [comment]
Yes. The packaging itself is not an issue. 

The issue arises when trying to pull the package from pip (I could also reproduce locally). When packaging using sdist, ```README.md``` is not included. Therefore, pip cannot install the package locally (as it is referenced by the setup function in setup.py).

#5 fixes that. I verified that locally

**Pull request closed without merging**
